---
openapi: 3.0.1
info:
  title: Eedrisserh-API v1
  version: v1
paths:
  "/players":
    get:
      summary: list Players
      tags:
      - Players
      responses:
        '200':
          description: successful
    post:
      summary: create player
      tags:
      - Players
      responses:
        '200':
          description: successful
  "/players/new":
    get:
      summary: new player
      tags:
      - Players
      responses:
        '200':
          description: successful
  "/players/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit player
      tags:
      - Players
      responses:
        '200':
          description: successful
  "/players/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show player
      tags:
      - Players
      responses:
        '200':
          description: successful
    patch:
      summary: update player
      tags:
      - Players
      responses:
        '200':
          description: successful
    put:
      summary: update player
      tags:
      - Players
      responses:
        '200':
          description: successful
    delete:
      summary: delete player
      tags:
      - Players
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:30/